# about.ini
# contains information about a feature
# java.io.Properties file (ISO 8859-1 with "\" escapes)
# "%key" are externalized strings defined in about.properties

# Blurb shown for this feature in Help > About > Installation Details
aboutText=%blurb

# 32x32 image shown for this feature in Help > About > Installation Details
featureImage=icons/feature32.png
