source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               about.ini,\
               about.properties,\
               about.mappings,\
               language-configurations/,\
               icons/,\
               syntaxes/
